### PR TITLE
Make graphaware/neo4j-php-ogm optional

### LINKED ISSUE #4: Make graphaware/neo4j-php-ogm an optional dependency

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #4

### CODE REVIEW

**Comment by xavismeh** [comment]
Great! Could you please remove `graphaware/neo4j-php-ogm` from `require` block in the composer.json file to move it to `suggest` block plz and squash your commits?

**Comment by Nyholm** [comment]
Thank you for the review. I've rebased my PR and made the changes you suggested.

**Comment by Nyholm** [comment]
Is this ready for merge?

**Comment by xavismeh** [comment]
Could you please squash your commits plz?

**Comment by Nyholm** [comment]
You can squash commits just before you merge. https://github.com/blog/2141-squash-your-commits

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
