### PR TITLE
Add ability to register event subscriber

### PR DESCRIPTION
**Pull request by Baachi**
Hey Guys,

I created a compiler pass, which adds the ability to register event subscribers/listeners via service tags.

### CODE REVIEW

**Comment by xavismeh** [comment]
Hello @Baachi,
Thanks for this (very first!) contribution. We did not implement this before because the original graphaware lib already have this feature and this is, by the way, what we use to log queries (see https://github.com/neo4j-contrib/neo4j-symfony/blob/master/EventSubscriber/LoggerSubscriber.php).
Do you have a use case where this would not be good enough?

**Comment by Baachi** [comment]
Hey @xavismeh,

sure if you want to use the OGM you have to use the `EventManager`. Especially we use the preFlush/postFlush/onFlush events from OGM, which is only supported be EventManager.

https://github.com/graphaware/neo4j-php-ogm/blob/master/src/UnitOfWork.php#L200-L202

**Comment by xavismeh** [comment]
If I understand correctly your need, you might want to do something like this (not tested):
```php
<?php

use Doctrine\Common\EventSubscriber;
use GraphAware\Neo4j\OGM\Event\PreFlushEventArgs;

class myCustomSubscriber implements EventSubscriber
{
    public function getSubscribedEvents()
    {
        return ['onPreFlush'];
    }

    public function onPreFlush(PreFlushEventArgs $event)
    {
        // ... my custom logic
    }
}
```

**Comment by Baachi** [comment]
Exactly :)

**Comment by Baachi** [comment]
@xavismeh Ping :)

**Comment by xavismeh** [comment]
As mentioned earlier, you can use the default event dispatcher using the events defined in `GraphAware\Neo4j\Client\Neo4jClientEvents`

**Pull request closed without merging**
