### PR TITLE
twig typo fix

### PR DESCRIPTION
**Pull request by theUm**
Just one little typo that blocks twig renderer in _profiler route

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you!

**Comment by ikwattro** [comment]
@Nyholm What does prevent this PR to be merged ?

**Comment by Nyholm** [comment]
ah, nothing. I saw this PR the same minute it was submitted. I was just waiting on Travis and then I forgot. 

Thank you for the reminder.

**Comment by theUm** [comment]
Automated test failed - minimal PHP version in composer is 7.0, but in test environment 5.6 is used. Plz fix that :)

**Comment by Nyholm** [comment]
Im not sure what you mean. We do not test with 5.6. See https://travis-ci.org/neo4j-contrib/neo4j-symfony/builds/219224802

**Comment by theUm** [comment]
Uhh sorry, all ok i guess. I just saw 2/3 checks are passed red cross on the latest commit and assumed that merge failed

**Comment by lrlopez** [comment]
@Nyholm, are you going to launch a new release with the fix soon? The last tagged version, which is the default one installed by composer, does still have the typo. Thanks!

**Comment by Nyholm** [comment]
Naturally. I released 0.3.1 now. 

Thank you for the ping

**Pull request merged**
