### PR TITLE
Improve the profiler and data collector

### PR DESCRIPTION
**Pull request by Nyholm**
Using Symfonys event dispatcher
Created a service for connection manager
Updated the DataCollector and profiler page
Using a LoggerSubscriber

### CODE REVIEW

**Comment by xavismeh** [comment]
Why not enabling this feature by default for dev environment ?

**Comment by Nyholm** [comment]
It does not care about the environment. It only cares if the Kernel is in debug or not. (As it usually is in dev environment). By default, it is on when kernel.debug = true.

**Comment by Nyholm** [comment]
Is this the last PR to be merged before we can finish the test app?

**Comment by Nyholm** [comment]
Hey @xavismeh. Do you have time to review this? Should we find a date together where we can create a first version of this project?

**Comment by Nyholm** [comment]
Thank you for the review and the fixes.

**Pull request merged**
